<?php

namespace Bgarb002\Markdown\Parser;

/**
 * Types of tokens that could be generated by the lexer.
 */
enum TokenType: string
{
    case CHAR = 'CHAR';
    case LINK = 'LINK';
    case HEADER = 'HEADER';
    case NEWLINE = 'NEWLINE';
    case EOF = 'EOF';
}
